package com.example.count_out.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF004D78)
val onPrimaryLight = Color(0xFF626262) // Text default color (TextApp)
val primaryContainerLight = Color(0xFF2373A9)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF026398)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF5EA3DC)
val onSecondaryContainerLight = Color(0xFF00101F)
val tertiaryLight = Color(0xFF3E6281)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFA4C8EC)
val onTertiaryContainerLight = Color(0xFF0D3755)
val errorLight = Color(0xFF9E0054)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFDB1F79)
val onErrorContainerLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFF8F9FE)  //Common background application
val onBackgroundLight = Color(0xFF5F5F5F) //Common text
val surfaceLight = Color(0xFFF8F9FE)
val onSurfaceLight = Color(0xFF8D67FF)
val surfaceVariantLight = Color(0xFFDCE3ED)
val onSurfaceVariantLight = Color(0xFF40474F)  //Lower-emphasis color for text and icons against any surface color
val outlineLight = Color(0xFF8D67FF)           // Selected element
val outlineVariantLight = Color(0xFFC0C7D1)
val scrimLight = Color(0xFFE11313)
val inverseSurfaceLight = Color(0xFF2D3134)
val inverseOnSurfaceLight = Color(0xFFEFF1F6)
val inversePrimaryLight = Color(0xFF94CCFF)
val surfaceDimLight = Color(0xFFD8DADF)
val surfaceBrightLight = Color(0xFFF8F9FE)
val surfaceContainerLowestLight = Color(0xFFE1E1E1) //3 level Frame 0xFF797979
val surfaceContainerLowLight = Color(0xFFDCDCDC)    //2 level frame 0xFF9F9F9F
val surfaceContainerLight = Color(0xFFE8E8E8)       //BottomBar background
val surfaceContainerHighLight = Color(0xFFBDBDBD)   //1 level Frame 0xFFE1E1E1
val surfaceContainerHighestLight = Color(0xFFE0E0E0) // Card background

val primaryDark = Color(0xFF94CCFF)
val onPrimaryDark = Color(0xFF003352)
val primaryContainerDark = Color(0xFF005888)
val onPrimaryContainerDark = Color(0xFFF2F7FF)
val secondaryDark = Color(0xFF94CCFF)
val onSecondaryDark = Color(0xFF003352)
val secondaryContainerDark = Color(0xFF2E7AB0)
val onSecondaryContainerDark = Color(0xFFFFFFFF)
val tertiaryDark = Color(0xFFC6E1FF)
val onTertiaryDark = Color(0xFF063350)
val tertiaryContainerDark = Color(0xFF95B8DC)
val onTertiaryContainerDark = Color(0xFF002B47)
val errorDark = Color(0xFFFFB1C8)
val onErrorDark = Color(0xFF650033)
val errorContainerDark = Color(0xFFB70062)
val onErrorContainerDark = Color(0xFFFFFFFF)
val backgroundDark = Color(0xFF101417)
val onBackgroundDark = Color(0xFFE1E2E7)
val surfaceDark = Color(0xFF101417)
val onSurfaceDark = Color(0xFFE1E2E7)
val surfaceVariantDark = Color(0xFF40474F)
val onSurfaceVariantDark = Color(0xFFC0C7D1)
val outlineDark = Color(0xFF8A919A)
val outlineVariantDark = Color(0xFF40474F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E2E7)
val inverseOnSurfaceDark = Color(0xFF2D3134)
val inversePrimaryDark = Color(0xFF016398)
val surfaceDimDark = Color(0xFF101417)
val surfaceBrightDark = Color(0xFF36393D)
val surfaceContainerLowestDark = Color(0xFF0B0F12)
val surfaceContainerLowDark = Color(0xFF191C1F)
val surfaceContainerDark = Color(0xFF1D2024)
val surfaceContainerHighDark = Color(0xFF272A2E)
val surfaceContainerHighestDark = Color(0xFF323539)

val primaryLightMediumContrast = Color(0xFF00466E)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF2373A9)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF00466E)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF2E7AB0)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF204664)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF547899)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF870046)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDB1F79)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF8F9FE)
val onBackgroundLightMediumContrast = Color(0xFF191C1F)
val surfaceLightMediumContrast = Color(0xFFF8F9FE)
val onSurfaceLightMediumContrast = Color(0xFF191C1F)
val surfaceVariantLightMediumContrast = Color(0xFFDCE3ED)
val onSurfaceVariantLightMediumContrast = Color(0xFF3C444B)
val outlineLightMediumContrast = Color(0xFF596068)
val outlineVariantLightMediumContrast = Color(0xFF747B84)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2D3134)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEFF1F6)
val inversePrimaryLightMediumContrast = Color(0xFF94CCFF)
val surfaceDimLightMediumContrast = Color(0xFFD8DADF)
val surfaceBrightLightMediumContrast = Color(0xFFF8F9FE)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF2F3F8)
val surfaceContainerLightMediumContrast = Color(0xFFECEEF3)
val surfaceContainerHighLightMediumContrast = Color(0xFFE6E8ED)
val surfaceContainerHighestLightMediumContrast = Color(0xFFE1E2E7)

val primaryDarkMediumContrast = Color(0xFF9DD0FF)
val onPrimaryDarkMediumContrast = Color(0xFF00182A)
val primaryContainerDarkMediumContrast = Color(0xFF5096CE)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFF9DD0FF)
val onSecondaryDarkMediumContrast = Color(0xFF00182A)
val secondaryContainerDarkMediumContrast = Color(0xFF5096CE)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFC6E1FF)
val onTertiaryDarkMediumContrast = Color(0xFF002944)
val tertiaryContainerDarkMediumContrast = Color(0xFF95B8DC)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFB7CC)
val onErrorDarkMediumContrast = Color(0xFF350018)
val errorContainerDarkMediumContrast = Color(0xFFFF4896)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF101417)
val onBackgroundDarkMediumContrast = Color(0xFFE1E2E7)
val surfaceDarkMediumContrast = Color(0xFF101417)
val onSurfaceDarkMediumContrast = Color(0xFFF9FAFF)
val surfaceVariantDarkMediumContrast = Color(0xFF40474F)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC4CBD5)
val outlineDarkMediumContrast = Color(0xFF9CA3AD)
val outlineVariantDarkMediumContrast = Color(0xFF7D848C)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE1E2E7)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF272A2E)
val inversePrimaryDarkMediumContrast = Color(0xFF004C76)
val surfaceDimDarkMediumContrast = Color(0xFF101417)
val surfaceBrightDarkMediumContrast = Color(0xFF36393D)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0B0F12)
val surfaceContainerLowDarkMediumContrast = Color(0xFF191C1F)
val surfaceContainerDarkMediumContrast = Color(0xFF1D2024)
val surfaceContainerHighDarkMediumContrast = Color(0xFF272A2E)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF323539)

val primaryLightHighContrast = Color(0xFF00243C)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF00466E)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF00243C)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF00466E)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF00243C)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF204664)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4B0024)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF870046)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF8F9FE)
val onBackgroundLightHighContrast = Color(0xFF191C1F)
val surfaceLightHighContrast = Color(0xFFF8F9FE)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDCE3ED)
val onSurfaceVariantLightHighContrast = Color(0xFF1E252C)
val outlineLightHighContrast = Color(0xFF3C444B)
val outlineVariantLightHighContrast = Color(0xFF3C444B)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2D3134)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFDFEEFF)
val surfaceDimLightHighContrast = Color(0xFFD8DADF)
val surfaceBrightLightHighContrast = Color(0xFFF8F9FE)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF2F3F8)
val surfaceContainerLightHighContrast = Color(0xFFECEEF3)
val surfaceContainerHighLightHighContrast = Color(0xFFE6E8ED)
val surfaceContainerHighestLightHighContrast = Color(0xFFE1E2E7)

val primaryDarkHighContrast = Color(0xFFF9FAFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF9DD0FF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFF9FAFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF9DD0FF)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFF9FAFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFAACEF3)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFB7CC)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF101417)
val onBackgroundDarkHighContrast = Color(0xFFE1E2E7)
val surfaceDarkHighContrast = Color(0xFF101417)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF40474F)
val onSurfaceVariantDarkHighContrast = Color(0xFFF9FAFF)
val outlineDarkHighContrast = Color(0xFFC4CBD5)
val outlineVariantDarkHighContrast = Color(0xFFC4CBD5)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE1E2E7)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF002D48)
val surfaceDimDarkHighContrast = Color(0xFF101417)
val surfaceBrightDarkHighContrast = Color(0xFF36393D)
val surfaceContainerLowestDarkHighContrast = Color(0xFF0B0F12)
val surfaceContainerLowDarkHighContrast = Color(0xFF191C1F)
val surfaceContainerDarkHighContrast = Color(0xFF1D2024)
val surfaceContainerHighDarkHighContrast = Color(0xFF272A2E)
val surfaceContainerHighestDarkHighContrast = Color(0xFF323539)


val TextDate = Color(0xFF9C9C9C)
val SectionColor = Color(0x22909EE7)


val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val md_theme_light_primary = Color(0xFFC7D7E7)
val md_theme_light_onPrimary = Color(0xFF03123F)
val md_theme_light_primaryContainer = Color(0xFFD7E2FF) //0xFFD7E2FF
val md_theme_light_onPrimaryContainer = Color(0xFF001A40)
val md_theme_light_secondary = Color(0xFFD7E4F0)
val md_theme_light_onSecondary = Color(0xFF03123F)
val md_theme_light_secondaryContainer = Color(0xFFC2E8FF) //0xFFC2E8FF
val md_theme_light_onSecondaryContainer = Color(0xFF001E2B)
val md_theme_light_tertiary = Color(0xFFDCEBF9)
val md_theme_light_onTertiary = Color(0xFF03123F)
val md_theme_light_tertiaryContainer = Color(0xFFE7EBFD) //0xFFCCE5FF
val md_theme_light_onTertiaryContainer = Color(0xFF001E31)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF1F3FF)  //0xFFF1F3FF
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFEBEFF6)  //0xFF5D8BBA
val md_theme_light_onSurface = Color(0xFF32385A)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44474E)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFFACC7FF)
val md_theme_light_surfaceTint = Color(0xFF2F5DA8)
val md_theme_light_outlineVariant = Color(0xFFC4C6D0)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surfaceContainer = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFACC7FF)
val md_theme_dark_onPrimary = Color(0xFF002F67)
val md_theme_dark_primaryContainer = Color(0xFF0A458E)
val md_theme_dark_onPrimaryContainer = Color(0xFFD7E2FF)
val md_theme_dark_secondary = Color(0xFF76D1FF)
val md_theme_dark_onSecondary = Color(0xFF003548)
val md_theme_dark_secondaryContainer = Color(0xFF004D67)
val md_theme_dark_onSecondaryContainer = Color(0xFFC2E8FF)
val md_theme_dark_tertiary = Color(0xFF92CCFF)
val md_theme_dark_onTertiary = Color(0xFF003351)
val md_theme_dark_tertiaryContainer = Color(0xFF004B73)
val md_theme_dark_onTertiaryContainer = Color(0xFFCCE5FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1B1F) //0xFF1B1B1F
val md_theme_dark_onBackground = Color(0xFFE3E2E6)
val md_theme_dark_surface = Color(0xFF3D3D46)
val md_theme_dark_onSurface = Color(0xFFE3E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF44474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE3E2E6)
val md_theme_dark_inversePrimary = Color(0xFF2F5DA8)
val md_theme_dark_surfaceTint = Color(0xFFACC7FF)
val md_theme_dark_outlineVariant = Color(0xFF44474E)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF004089)

// Основные цвета:
val Black = Color(0xFF000000)
val Gray = Color(0xFF808080)
val Silver = Color(0xFFC0C0C0)
val White = Color(0xFFFFFFFF)
val Fuchsia = Color(0xFFFF00FF)
val Purple = Color(0xFF800080)
val Red = Color(0xFFFF0000)
val Maroon = Color(0xFF800000)
val Yellow = Color(0xFFFFFF00)
val Olive = Color(0xFF808000)
val Lime = Color(0xFF00FF00)
val Green = Color(0xFF008000)
val Aqua = Color(0xFF00FFFF)
val Teal = Color(0xFF008080)
val Blue = Color(0xFF0000FF)
val Navy = Color(0xFF000080)
//Красные тона
val IndianRed = Color(0xFFCD5C5C)
val LightCoral = Color(0xFFF08080)
val Salmon = Color(0xFFFA8072)
val DarkSalmon = Color(0xFFE9967A)
val LightSalmon1 = Color(0xFFFFA07A)
val Crimson = Color(0xFFDC143C)
val Red1 = Color(0xFFFF0000)
val FireBrick = Color(0xFFB22222)
val DarkRed = Color(0xFF8B0000)
// Розовые тона:
val Pink = Color(0xFFFFC0CB)
val LightPink = Color(0xFFFFB6C1)
val HotPink = Color(0xFFFF69B4)
val DeepPink = Color(0xFFFF1493)
val MediumVioletRed = Color(0xFFC71585)
val PaleVioletRed = Color(0xFFDB7093)
// Оранжевые тона:
val LightSalmon = Color(0xFFFFA07A)
val Coral = Color(0xFFFF7F50)
val Tomato = Color(0xFFFF6347)
val OrangeRed = Color(0xFFFF4500)
val DarkOrange = Color(0xFFFF8C00)
val Orange = Color(0xFFFFA500)
// Жёлтые тона:
val Gold = Color(0xFFFFD700)
val Yellow1 = Color(0xFFFFFF00)
val LightYellow = Color(0xFFFFFFE0)
val LemonChiffon = Color(0xFFFFFACD)
val LightGoldenrodYellow = Color(0xFFFAFAD2)
val PapayaWhip = Color(0xFFFFEFD5)
val Moccasin = Color(0xFFFFE4B5)
val PeachPuff = Color(0xFFFFDAB9)
val PaleGoldenrod = Color(0xFFEEE8AA)
val Khaki = Color(0xFFF0E68C)
val DarkKhaki = Color(0xFFBDB76B)
// Фиолетовые тона:
val Lavender = Color(0xFFE6E6FA)
val Thistle = Color(0xFFD8BFD8)
val Plum = Color(0xFFDDA0DD)
val Violet = Color(0xFFEE82EE)
val Orchid = Color(0xFFDA70D6)
val Fuchsia1 = Color(0xFFFF00FF)
val Magenta = Color(0xFFFF00FF)
val MediumOrchid = Color(0xFFBA55D3)
val MediumPurple = Color(0xFF9370DB)
val BlueViolet = Color(0xFF8A2BE2)
val DarkViolet = Color(0xFF9400D3)
val DarkOrchid = Color(0xFF9932CC)
val DarkMagenta = Color(0xFF8B008B)
val Purple1 = Color(0xFF800080)
val Indigo = Color(0xFF4B0082)
val SlateBlue = Color(0xFF6A5ACD)
val DarkSlateBlue = Color(0xFF483D8B)
// Коричневые тона:
val Cornsilk = Color(0xFFFFF8DC)
val BlanchedAlmond = Color(0xFFFFEBCD)
val Bisque = Color(0xFFFFE4C4)
val NavajoWhite = Color(0xFFFFDEAD)
val Wheat = Color(0xFFF5DEB3)
val BurlyWood = Color(0xFFDEB887)
val Tan = Color(0xFFD2B48C)
val RosyBrown = Color(0xFFBC8F8F)
val SandyBrown = Color(0xFFF4A460)
val Goldenrod = Color(0xFFDAA520)
val DarkGoldenRod = Color(0xFFB8860B)
val Peru = Color(0xFFCD853F)
val Chocolate = Color(0xFFD2691E)
val SaddleBrown = Color(0xFF8B4513)
val Sienna = Color(0xFFA0522D)
val Brown = Color(0xFFA52A2A)
val Maroon1 = Color(0xFF800000)

// Зелёные тона:
val GreenYellow = Color(0xFFADFF2F)
val Chartreuse = Color(0xFF7FFF00)
val LawnGreen = Color(0xFF7CFC00)
val Lime1 = Color(0xFF00FF00)
val LimeGreen = Color(0xFF32CD32)
val PaleGreen = Color(0xFF98FB98)
val LightGreen = Color(0xFF90EE90)
val MediumSpringGreen = Color(0xFF00FA9A)
val SpringGreen = Color(0xFF00FF7F)
val MediumSeaGreen = Color(0xFF3CB371)
val SeaGreen = Color(0xFF2E8B57)
val ForestGreen = Color(0xFF228B22)
val Green1 = Color(0xFF008000)
val DarkGreen = Color(0xFF006400)
val YellowGreen = Color(0xFF9ACD32)
val OliveDrab = Color(0xFF6B8E23)
val Olive1 = Color(0xFF808000)
val DarkOliveGreen = Color(0xFF556B2F)
val MediumAquamarine = Color(0xFF66CDAA)
val DarkSeaGreen = Color(0xFF8FBC8F)
val LightSeaGreen = Color(0xFF20B2AA)
val DarkCyan = Color(0xFF008B8B)
val Teal1 = Color(0xFF008080)
// Синие тона:
val Aqua1 = Color(0xFF00FFFF)
val Cyan = Color(0xFF00FFFF)
val LightCyan = Color(0xFFE0FFFF)
val PaleTurquoise = Color(0xFFAFEEEE)
val Aquamarine = Color(0xFF7FFFD4)
val Turquoise = Color(0xFF40E0D0)
val MediumTurquoise = Color(0xFF48D1CC)
val DarkTurquoise = Color(0xFF00CED1)
val CadetBlue = Color(0xFF5F9EA0)
val SteelBlue = Color(0xFF4682B4)
val LightSteelBlue = Color(0xFFB0C4DE)
val PowderBlue = Color(0xFFB0E0E6)
val LightBlue = Color(0xFFADD8E6)
val SkyBlue = Color(0xFF87CEEB)
val LightSkyBlue = Color(0xFF87CEFA)
val DeepSkyBlue = Color(0xFF00BFFF)
val DodgerBlue = Color(0xFF1E90FF)
val CornflowerBlue = Color(0xFF6495ED)
val MediumSlateBlue = Color(0xFF7B68EE)
val RoyalBlue = Color(0xFF4169E1)
val Blue1 = Color(0xFF0000FF)
val MediumBlue = Color(0xFF0000CD)
val DarkBlue = Color(0xFF00008B)
val Navy1 = Color(0xFF000080)
val MidnightBlue = Color(0xFF191970)
// Белые тона:
val White1 = Color(0xFFFFFFFF)
val Snow = Color(0xFFFFFAFA)
val Honeydew = Color(0xFFF0FFF0)
val MintCream = Color(0xFFF5FFFA)
val Azure = Color(0xFFF0FFFF)
val AliceBlue = Color(0xFFF0F8FF)
val GhostWhite = Color(0xFFF8F8FF)
val WhiteSmoke = Color(0xFFF5F5F5)
val Seashell = Color(0xFFFFF5EE)
val Beige = Color(0xFFF5F5DC)
val OldLace = Color(0xFFFDF5E6)
val FloralWhite = Color(0xFFFFFAF0)
val Ivory = Color(0xFFFFFFF0)
val AntiqueWhite = Color(0xFFFAEBD7)
val Linen = Color(0xFFFAF0E6)
val LavenderBlush = Color(0xFFFFF0F5)
val MistyRose = Color(0xFFFFE4E1)
// Серые тона:
val Gainsboro = Color(0xFFDCDCDC)
val LightGrey = Color(0xFFD3D3D3)
val LightGray = Color(0xFFD3D3D3)
val Silver1 = Color(0xFFC0C0C0)
val DarkGray = Color(0xFFA9A9A9)
val DarkGrey = Color(0xFFA9A9A9)
val Gray1 = Color(0xFF808080)
val Grey = Color(0xFF808080)
val DimGray = Color(0xFF696969)
val DimGrey = Color(0xFF696969)
val LightSlateGray = Color(0xFF778899)
val LightSlateGrey = Color(0xFF778899)
val SlateGray = Color(0xFF708090)
val SlateGrey = Color(0xFF708090)
val DarkSlateGray = Color(0xFF2F4F4F)
val DarkSlateGrey = Color(0xFF2F4F4F)
val Black1 = Color(0xFF000000)

val massColor = listOf(
    // Основные цвета
    listOf(Black, Gray, Silver, White, Fuchsia, Purple, Red, Maroon, Yellow, Olive, Lime, Green, Aqua, Teal, Blue, Navy),
    // Розовые тона
    listOf(IndianRed, LightCoral, Salmon, DarkSalmon, LightSalmon1, Crimson, Red1, FireBrick, DarkRed),
    // Оранжевые тона
    listOf(LightSalmon, Coral, Tomato, OrangeRed, DarkOrange, Orange),
    // Жёлтые тона
    listOf(Gold, Yellow1, LightYellow, LemonChiffon, LightGoldenrodYellow, PapayaWhip, Moccasin, PeachPuff, PaleGoldenrod, Khaki, DarkKhaki),
    // Фиолетовые тона
    listOf(Lavender, Thistle, Plum, Violet, Orchid, Fuchsia1, Magenta, MediumOrchid, MediumPurple, BlueViolet, DarkViolet, DarkOrchid, DarkMagenta, Purple1, Indigo, SlateBlue, DarkSlateBlue),
    // Коричневые тона
    listOf(Cornsilk, BlanchedAlmond, Bisque, NavajoWhite, Wheat, BurlyWood, Tan, RosyBrown, SandyBrown, Goldenrod, DarkGoldenRod, Peru, Chocolate, SaddleBrown, Sienna, Brown, Maroon1),
    // Зелёные тона
    listOf(GreenYellow, Chartreuse, LawnGreen, Lime1, LimeGreen, PaleGreen, LightGreen, MediumSpringGreen, SpringGreen, MediumSeaGreen, SeaGreen, ForestGreen, Green1, DarkGreen, YellowGreen, OliveDrab, Olive1, DarkOliveGreen, MediumAquamarine, DarkSeaGreen, LightSeaGreen, DarkCyan, Teal1),
    // Синие тона
    listOf(Aqua1, Cyan, LightCyan, PaleTurquoise, Aquamarine, Turquoise, MediumTurquoise, DarkTurquoise, CadetBlue, SteelBlue, LightSteelBlue, PowderBlue, LightBlue, SkyBlue, LightSkyBlue, DeepSkyBlue, DodgerBlue, CornflowerBlue, MediumSlateBlue, RoyalBlue, Blue1, MediumBlue, DarkBlue, Navy1, MidnightBlue),
    // Белые тона
    listOf(White1, Snow, Honeydew, MintCream, Azure, AliceBlue, GhostWhite, WhiteSmoke, Seashell, Beige, OldLace, FloralWhite, Ivory, AntiqueWhite, Linen, LavenderBlush, MistyRose),
    // Серые тона
    listOf(Gainsboro, LightGrey, LightGray, Silver1, DarkGray, DarkGrey, Gray1, Grey, DimGray, DimGrey, LightSlateGray, LightSlateGrey, SlateGray, SlateGrey, DarkSlateGray, DarkSlateGrey, Black1),
)
