package com.count_out.framework.room.db.old.set


//
//@Entity(tableName = "tb_set")
//data class SetTable (
//    @PrimaryKey(autoGenerate = true)  var idSet: Long = 0L,
//    var name: String = "",
//    var speechId: Long = 0,
//    var goal: Int = 1,
//    var exerciseId: Long = 0,
//    var reps: Int = 0,
//    var duration1: Double = 0.0,
//    var durationU: Int = Units.S.ordinal,
//    var distance: Double = 0.0,
//    var distanceU: Int = Units.MT.ordinal,
//    var weight: Double = 0.0,
//    var weightU: Int = Units.GR.ordinal,
//    var intervalReps: Double = 0.0,
//    var intensity: Int = 1,
//    var intervalDown: Int = 0,
//    var groupCount: String = "",
//    var timeRest: Double = 0.0,
//    var timeRestU: Int = Units.S.ordinal,
//){
//    constructor(set: SetImplD): this(
//        idSet = set.idSet,
//        name = set.name,
//        speechId = set.speechId,
//        goal = set.goal.ordinal,
//        exerciseId = set.exerciseId,
//        reps = set.reps,
//        duration1 = set.duration.value,
//        durationU = set.duration.unit.ordinal,
//        distance = set.distance.value,
//        distanceU = set.distance.unit.ordinal,
//        weight = set.weight.value,
//        weightU = set.weight.unit.ordinal,
//        intervalReps = set.intervalReps,
//        intensity = set.intensity.ordinal,
//        intervalDown = set.intervalDown,
//        groupCount = set.groupCount,
//        timeRest = set.rest.value,
//        timeRestU = set.rest.unit.ordinal,
//    )
//    constructor(set: SetImplD, id: Long = set.idSet, idSpeech: Long = set.speechId): this(
//        idSet = id,
//        name = set.name,
//        speechId = idSpeech,
//        goal = set.goal.ordinal,
//        exerciseId = set.exerciseId,
//        reps = set.reps,
//        duration1 = set.duration.value,
//        durationU = set.duration.unit.ordinal,
//        distance = set.distance.value,
//        distanceU = set.distance.unit.ordinal,
//        weight = set.weight.value,
//        weightU = set.weight.unit.ordinal,
//        intervalReps = set.intervalReps,
//        intensity = set.intensity.ordinal,
//        intervalDown = set.intervalDown,
//        groupCount = set.groupCount,
//        timeRest = set.rest.value,
//        timeRestU = set.rest.unit.ordinal,
//    )
//}